
== Platform
The page `Platform` contains all elements regarding the installed appNG platform.

=== Configuring the platform
The first section of the page `Platform` lists the platform properties. A platform property can be created, deleted and edited.

Platform properties are created during the first (initial) startup of the platform. The default values are defined within the appNG platform. The default value may be overwritten during a platform update.

As long as the value or the multilined value of a property is not defined, appNG uses the default value.

=== Platform properties

include::./platform-properties.adoc[]

==== Edit platform property
Each property in the list of platform properties offers an action to edit it. By clicking this action a new form opens where the value or the multilined value of a property can be changed. Note that it is not possible to save the property if both fields are filled.

If the value or multilined value is defined, appNG will use this new value after a platform reload. Empty the value or multilined value field if appNG should use the default again.

==== Create platform property
On top and bottom of the table an action to create a platform property is displayed. The new property has to have an unique name. The given value will be used as default value. Creating a property can be used to activate and configure features for appNG not available in the default configuration. Properties can also be used as feature toggles to activate and configure new features during appNG platform development.

==== Delete platform property
Each property in the list can be deleted. For standard properties this makes no sense because the property will be recreated after a platform reload. Manually created properties can be deleted.

=== Reloading the platform
On top and bottom of the table an action to reload the platform is displayed. This action reinitializes the platform configuration and reloads all sites without restarting the whole Tomcat instance.

=== Managing the platform's database connection
appNG stores all its configuration data like platform properties, sites, applications properties, site properties, site-specific application properties and also entire application resources in a database. The database is a fundamental component of each appNG installation.

The platform page has a section to manage the database connection. appNG currently supports three different kinds of database servers. Database connections are pre-configured for those database servers. Only one of them is active after a default installation.

Supported database servers are:

* MYSQL
* MSSQL
* HSQL

HSQL is used for executing integration tests and for the appNG standalone version. For production use we recommend to use either MySQL or MSSQL.

==== Editing a database connection

This section allows to modify the existing database connections. It is not supported to delete or create database connections. To edit a database connection click on the table row or the edit action within a row. A new form opens where the database connection attributes can be maintained:

[cols="20,60,20",width="100%",options="header"]
|====================
| Attribute Name | Description | Example
| Type  | The type of the database. | MYSQL
| Name | The name of the database. | `appNG MYSQL`
| JDBC-URL | The JDBC url used to connect to the database. | `jdbc:mysql://localhost:3306/appng`
| User-Name | The name of the user used to connect to the database. | `appng`
| Password | The password used to authenticate the database user.  | `Xoos9Eeng1ku`
| Driver-Class | The name of the `java.sql.Driver` implementation used to connect to the database. | `com.mysql.jdbc.Driver`
| managed | Flag to indicate whether the database is managed by appNG or not. If the database is not managed by appNG, a database administrator has to take care of creating databases for the platform as well as for applications requesting a database. | `true`
| active | Flag to indicate whether this connection can be used by appNG.|`yes` 
| Min. number of connections | appNG uses connection pooling to avoid the overhead by opening and closing JDBC connections. This value defines the minimum number of connections in the pool. Default value is `1`. | `1`
| Max. number of connections | This value defines the maximum number of open JDBC connections in that pool. Default value is `20`. | `20`
| Validation query | appNG checks if the database is properly connected. Therefore it needs to execute a query. Default for mysql databases is `select 1`. | `select 1`
| Description | The Administrator can add some more information about the connection. | appNG Root Database
|====================

====
[NOTE]
appNG can use database connections to different types of database servers at the same time. *TODO: Explain, example, order of supported databases in `application.xml`*
====

=== JAR-Files
The section `JAR-Files` lists all Java archive files of the platform and JAR files which are provided by the Tomcat runtime environment. File name, version, title and vendor are displayed. This is useful to verify the version of the used libraries. It also helps to include library versions in bug reports. The information displayed here is read from the `META-INF/MANIFEST.MF` of the respective library. If information is missing for a certain library, its `MANIFEST.MF` is probably not well-maintained.

=== Events
There are certain events that occur within the appNG platform that are written to an event log. This event log can be shown, filtered and exported.

Events that are recorded include:

* starting/stopping the platform
* starting/stopping a site
* assigning/removing an application to/from a site
* user log-in and log-out, session expiration
* creating/dropping databases
* creating/modifing any of appNG's core components +
(sites, applications, users, groups, roles, permissions, resources and database connections)

A platform event has the following attributes:

[cols="20,60,20",width="100%",options="header"]
|====================
| Attribute Name | Description | Example
|Created|The date and time when the event occurred.|`18/04/17 12:37:49`
|Type|The type of the event. One of `CREATE`, `UPDATE`, `DELETE`, `INFO`,`ERROR`,`WARN`.|`INFO`
|Event|A text describing the event.|`Loaded site manager`
|Appplication|The application that triggered the event. One of `appNG`, `appNG CLI` or `appNGizer`|`appNG`
|Context|The context the event was executed in, depending onthe application that triggered the event. +
If it was triggered by `appNG` or `appNGizer`, the context is the relative URL path that caused the event. +
If triggered by `appNG CLI`, the context is the CLI command that caused the event|`/manager/manager/appng-manager/sites` +
`batch -f ./install.list`
|User|The user that triggered the event. This is either a user that was signed in at the appNG Manager, `appNG platform` (in case no specifix user could be determined), +
`appNGizer` (when triggered by the same) or, in case of an CLI command, the name of the system user that executed the command. |`appNG Administrator`
|Host|The remote host  or IP that triggered the event. May contain an IPv4 or IPv6 address or a host name.|`127.0.0.1`
|Host name|The local host name of the appNG server where the event was triggered at.|`appng-node1.example.com`
|Request|A universally unique identifier (UUID) for the request that triggered the event. Multiple events can be triggered by the same request.|`ba81aa7b-069b-4ed4-954e-7050f3a59da6`
|Session|The first 8 characters of the HTTP session, if applicable (only the case when triggered by `appNG` or `appNGizer`).|`D809E5C5`
|====================


=== Dictionary
This section shows the content of the platform dictionary.
