== Platform
The page `Platform` contains all elements regarding the installed appNG platform.

=== Configuring the platform
The first section of the page `Platform` lists the platform properties. A platform property can be created, deleted and edited.

Platform properties are created on first initial startup of the platform. It's default values are defined within the appNG platform. The default value may be overwritten after platform update.

As long as the value or the clob value of a property isn't defined, appNG uses the default value.

==== Edit platform property
Each property in the list of platform properties offers an action to edit the property. By clicking this action a new form opens where the value or the clob value of a property can be changed.

If the value is defined, appNG will use this new value after platform reload. Empty the value and clob value field again if appNG should use the default again.

=== Delete platform property
Each property in the list can be deleted. For standard properties this makes no sense because the property will be recreated after platform reload. Other, manually created properties can be deleted.

=== Create platform property
On top and bottom of the table is a action to create a platform property. The new property has to have an unique name. The given value will be used as default value. Creating a property maybe makes sense to do some hidden configuration for appNG.

=== Reloading the platform
On top and bottom of the table is a action to reload the platform. This action reinitializes the platform configuration and reloads all sites without restarting the whole tomcat instance.

=== Managing the platform's database connection
AppNG stores all it's configuration data like properties, sites, site properties, site application properties, applications properties and maybe entire application resources in a database. The database is a fundamental component of an appNG installation.

The platform page has a section to manage the database connection. On installation there are the three supported types of database connections pre-configured. Only one of them is active.

Supported are:

* MYSQL
* MSSQL
* HSQL

==== Editing a database connection

This section allows to modify the existing database connections. It is not supported to delete or create database connections. To edit a database connection click on the table row or the edit action within a row. A new form opens where the database connection attributes can be maintained:

[width="100%",options="header"]
|====================
| Attribute Name | Description
| Name |  The name of the connection
| JDBC-URL | The java database connectivity (jdbc) address of the database.
| User-Name | user name for authentication
| Password | Password to be used for authentication
| Driver-Class | Java class to be used to create the jdbc connection
| managed | flag to indicate if the database is managed by appNG or not. If the database is not managed by appNG the operator of the platform has to take care about creating databases for applications requesting an database of that type as datasource.
| active | flag to indicate if this connection is the active connection to be used by appNG for that type of database.
| Min. number of connections | appNG uses connection pooling to avoid overhead by opening and closing of jdbc connections. This value defines the minimum number of connections in that pool. Default value is 1
| Max. number of connections | appNG uses connection pooling to avoid overhead by opening and closing of jdbc connections. This value defines the maximum number of open connections in that pool. Default value is 20
| Validation query | appNG want's to check if a database is properly connected. Therefore it needs to execute a query. Default for mysql databases is `select 1`
| Description | The Administrator can add some more information about the connection. Default is `appNG Root Database`
|====================


=== JAR-Files
The section `JAR-Files` lists all java archive files of the platform and jar files which are contained in the tomcat runtime environment. It shows the file name, version, title and vendor. This might be useful to verify the version of the used libraries. It also might help if a bug has to be reported.


=== Dictionary
This section shows the content of the platform dictionary.
