== System
This page shows information about the runtime system of the appNG platform.

=== Environment
==== JVM Arguments
Returns the input arguments passed to the Java virtual machine which does not include the arguments to the main method.

==== System Properties
Determines the current system properties. It does this by showing all values given by calling the static System method
[CODE]
====
java.lang.System.getProperties()
====

==== System Environment
Determines the current system environment. The environment is a system-dependent mapping from names to values which is passed from parent to child processes. AppNG does this by calling
[CODE]
====
java.lang.System.getenv()
====

=== Status
The Status section gives some information about the system status
==== Processor
Shows the system load average for the last minute  and the number of processors available to the Java virtual machine.

==== Memory
Determines the current memory usage of the heap that is used for object allocation and the current memory usage of non-heap memory that is used by the Java virtual machine.

==== Sessions
List all session currently active for the platform. Allows to expire one or all sessions if it is not the session of the current user.

=== Logfile
Shows a tail view of the appNG logfile from the current node. If appNG runs in a cluster setup be aware that there are other logfiles on other nodes.

It also shows the current log4j configuration in an editable text field. Changes on this content can be submitted. This will change the used log4j configuration immediately without platform reload. It is optionally possible to propagate this configuration to all other nodes in the cluster.

=== Cluster Status
This section shows the status of all other nodes in the cluster. A status consists of:

[width="100%",options="header,footer"]
|====================
| Status Item | Description|
| Node ID | Node Id defined as system property `appng.node.id`. Identifies a node within a cluster.
| Last Updated | The cluster status is directly called from the other nodes within the cluster. This timestamp shows when the data of this node have been retrieved
| Memory status | The current memory usage of the heap of that node that is used for object allocation.
|====================

Each entry can be enlaged to show also:

* List and status of all sites of that node.
* System properties of that node as shown in the <<Environment>> page of that node.
* System Environment of that node as shown in the <<Environment>> page of that node.
