
== Users and groups
appNG features a fine-grained user role and permission model. The key elements are:

[width="100%",options="header"]
|====================
| Element | Description
| permission | The right to see or do something. Permissions are defined by the application in the `application.xml` file. It can be applied to a lot of elements like actions, datasources, pages, linkpanels and fields. Furthermore, application developers can test a permission programmatically.
| role | An aggregation of permissions of one application. Roles are defined in the `application.xml` file.
| group | An aggregation of roles, also from different applications. Created and defined in the appNG manager. On installation the group `Administrators` is created by default. All admin roles from all default applications (appng-manager, appng-scheduler) are automatically assigned to that group.
| user | An account in appNG. Could be a pure appNG-local user or a user from an LDAP repository or Active Directory. A user can have multiple groups. In default installations, the user `admin` is created and gets assigned to the group `Administrators`.
|====================

Permissions are added to a user by assigning groups to users and roles to groups and permissions to roles. The assignment has always a contributing nature. It will not happen that an assignment will remove the permission set by another assignment. The user will always have the super-set of all permissions of all groups and roles assigned to him.

The users page shows a list of all configured users.

=== LDAP connectivity
If the type `LDAP user` or `LDAP Group` is used, the site has to be configured to be able to connect to a LDAP server. This can be configured with the following site properties:

[width="100%",options="header"]
|====================
| Property  | Description | Example
| `ldapDomain` | The Domain for the LDAP authentication | `EXAMPLE`
| `ldapGroupBaseDn` | The base-DN for LDAP-groups | `OU=Groups,DC=example,DC=com`
| `ldapHost` | The LDAP host | `ldap:<host>:<port>`
| `ldapIdAttribute` | The name of the LDAP-attribute containing the user-id used for authentication | `sAMAccountName`
| `ldapPassword` | Password of the LDAP service-user | `secret`
| `ldapUser` | The name of the LDAP service-user | `serviceUser`
| `ldapUserBaseDn` | The base-DN for LDAP-users | `OU=Users,DC=example,DC=com`
|====================

Read more about site properties in <<Configuring site properties>> in this manual.

=== Users

==== Creating a user
Above and below the users list a link with the action to create a user is displayed. When clicking this link a new form opens, where the user attributes can be defined:

[width="100%",options="header"]
|====================
| Attribute  | Description | Example
| Name | User name as used for the login. Must be unique. | `johndoe`
| Real Name | The person's real name | `John Doe`
| E-mail | E-Mail address of the person | `john.doe@example.com`
| Description | Some additional info about the user | `Just a test account`
| Type | One of `Local user`, `LDAP User` or `LDAP Group` | `Local user`
| Language | The preferred language of the user. Shows available appNG languages. | `en`
| Timezone | The users timezone | `Berlin (GMT+01:00)`
| Password | Must have at least 6 chars and max 64 chars | `v3ry53cr37`
| Password Confirmation | Must contain the same value as the `Password` field | `v3ry53cr37`
| Groups | Select initial groups of the user | `Administrators`
|====================

==== Editing a user
The default action of an entry in the users list is the action to edit a user. This opens a form where nearly all of the user attributes can be changed, except the internal ID and the user name.

=== Groups
On the page `Users` there is another section `Groups`. It lists all available groups configured in appNG. On appNG installation, the group Administrators is created. This is special group because if an application defines an admin-role in the `application.xml` file, this role is automatically assigned to this group. It is also not possible to delete this group.

The overview table provides actions to create, edit and delete groups.

==== Creating a group
When clicking the `Create group` action on top or bottom of the table, a new form opens where the attributes of the group can be defined:

[width="100%",options="header"]
|====================
| Attribute  | Description
| Name | Name of the group. Must be unique.
| Description | Some additional info about the group.
| Roles | Select roles from different applications to assign them to the group. Only roles of those applications are available which are assigned to the current site.
|====================

==== Editing a group
In the overview table of groups is an action per group to edit it. Except the internal ID, all attributes and the role assignment of the group can be changed.

==== Deleting a group
In the overview table of groups is an action per group to delete it. The group `Administrators` is a special group and cannot be deleted. After the deletion has been confirmed, the group and all assignments to users are completely removed.
